---
environment_variables:
  COMANAGE_SATOSA_VERSION: "experimental!! remember to change me later on!"

triggers:
  cron: "@daily"

git:
  branches:
    - master
clean_workspace: true

docker_name: satosa

builders:
  - docker

extra_jobs:
  - name: comanage-docker-satosa
    builders:
      - docker
    docker_name: comanage-docker-satosa
    git:
      branch: co_virtual_idp 
      extensions:
          checkout_local_branch: true


